apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-secret
  labels:
    app: {{ .Release.Name }}-grafana
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: YWRtaW4=        
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4xMjM=