apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-influxdb-secret
  labels:
    app: {{ .Release.Name }}-influxdb
type: Opaque
data:
  DOCKER_INFLUXDB_INIT_USERNAME: YWRtaW4=
  DOCKER_INFLUXDB_INIT_PASSWORD: QWRtaW5AMTIz
