apiVersion: v1
kind: Pod
metadata:
  name: test-connect-without-istio
  namespace: {{ .Values.namespace }}
  annotations:
    sidecar.istio.io/inject: "false"

spec:
  # Resolve the public hostname to the in-cluster Istio ingress gateway
  hostAliases:
    - ip: "10.141.218.208"
      hostnames:
        - islamic-channels.stgd.dhofarislamic.com
        - core.stgd.dhofarislamic.com
        - apihub.stgd.dhofarislamic.com

  containers:
    - name: netshoot
      image: harbor.cp.bankdhofar.com/internal-public/nicolaka/netshoot:latest
      imagePullPolicy: Always
      command:
        - sleep
        - infinity
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

  restartPolicy: Always