apiVersion: v1
kind: Pod
metadata:
  name: test-connect-without-istio
  namespace: {{ .Values.namespace }}
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
    - name: netshoot
      image: harbor.cp.bankdhofar.com/internal-public/nicolaka/netshoot:latest
      imagePullPolicy: Always
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
  restartPolicy: Always